"""
CreatorPulse — Interactive Demo (Streamlit Community Cloud)
===========================================================
A presentable, interactive front-end for the CreatorPulse burnout
early-warning analysis. It imports the analysis pipeline directly from
`creatorpulse_analysis.py` and renders the key results as a product-style
dashboard.

IMPORTANT: All data shown here is 100% SYNTHETIC and ILLUSTRATIVE. It is
generated by a simulator to demonstrate the analytics/ML methodology — it
does NOT describe any real creators.
"""

# Force a non-interactive matplotlib backend BEFORE anything imports pyplot,
# so importing the analysis module never tries to open a window / block.
import os
os.environ["MPLBACKEND"] = "Agg"
import matplotlib
matplotlib.use("Agg")

import io
import contextlib

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st
from sklearn.metrics import roc_curve, roc_auc_score, average_precision_score

# Import the analysis pipeline. The module guards its runner behind
# `if __name__ == "__main__":`, so importing it only defines functions —
# nothing runs, nothing blocks.
import creatorpulse_analysis as cp

# ─────────────────────────────────────────────────────────────────────────────
# PAGE CONFIG + THEME
# ─────────────────────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="CreatorPulse — Burnout Early Warning (Demo)",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="expanded",
)

sns.set_theme(style="whitegrid", palette="muted")

CARD_CSS = """
<style>
.block-container {padding-top: 2rem; padding-bottom: 3rem;}
.cp-banner {
    background: linear-gradient(90deg, #6d28d9 0%, #2563eb 100%);
    color: #fff; padding: 14px 20px; border-radius: 12px;
    font-size: 0.95rem; margin-bottom: 0.5rem;
}
.cp-pill {
    display:inline-block; background:#fde68a; color:#92400e;
    padding:2px 10px; border-radius:999px; font-weight:600; font-size:0.8rem;
}
small.cp-illu {color:#9ca3af; font-style:italic;}
</style>
"""
st.markdown(CARD_CSS, unsafe_allow_html=True)


# ─────────────────────────────────────────────────────────────────────────────
# DATA + ANALYSIS (cached so the heavy pipeline runs once per session)
# ─────────────────────────────────────────────────────────────────────────────
@st.cache_data(show_spinner="Generating synthetic data & running the analysis pipeline…")
def run_pipeline():
    """Run the analysis end-to-end and return every artifact the UI needs.

    All prints from the analysis are swallowed (redirected) so the Streamlit
    log stays clean; we only keep the returned objects.
    """
    buf = io.StringIO()
    with contextlib.redirect_stdout(buf):
        creators_df, ts_df = cp.section1_generate_data()
        burnout_by_arch = cp.section2_eda(creators_df, ts_df)
        p_mw, p_ttest, p_chi2 = cp.section3_hypothesis_testing(creators_df, ts_df)
        at_risk = cp.section4_ab_testing(creators_df)
        kmf_solo, kmf_team, survival_df = cp.section5_survival_analysis(creators_df)
        features_df = cp.section6_feature_engineering(creators_df, ts_df)
        gbm, feature_cols, y_test, y_prob = cp.section7_ml_model(features_df)
        did_estimate, p_did = cp.section8_causal_inference(ts_df)
        cohort_stats, creators_df = cp.section9_cohort_analysis(creators_df)

    # A/B summary numbers for the metric cards
    ab = at_risk.groupby("group").agg(
        n=("creator_id", "count"),
        resolved=("burnout_resolved", "mean"),
        retention=("retention_8w", "mean"),
    )

    return dict(
        creators_df=creators_df,
        ts_df=ts_df,
        burnout_by_arch=burnout_by_arch,
        p_mw=p_mw, p_ttest=p_ttest, p_chi2=p_chi2,
        at_risk=at_risk, ab=ab,
        kmf_solo=kmf_solo, kmf_team=kmf_team, survival_df=survival_df,
        features_df=features_df,
        gbm=gbm, feature_cols=feature_cols, y_test=y_test, y_prob=y_prob,
        did_estimate=did_estimate, p_did=p_did,
        cohort_stats=cohort_stats,
    )


R = run_pipeline()


# ─────────────────────────────────────────────────────────────────────────────
# HEADER + HONESTY BANNER
# ─────────────────────────────────────────────────────────────────────────────
st.title("📊 CreatorPulse")
st.subheader("Early-Warning System for Creator-Economy Burnout")

st.markdown(
    '<div class="cp-banner">⚠️ <b>Synthetic data — illustrative only.</b> '
    "Every number, chart, and model result on this page is produced from "
    "<b>100% simulated data</b> generated by a behavioral simulator. It exists to "
    "demonstrate the analytics &amp; ML methodology (survival analysis, A/B testing, "
    "gradient-boosted ML, causal inference) — it does <b>not</b> describe any real "
    "creators or platforms.</div>",
    unsafe_allow_html=True,
)

with st.sidebar:
    st.header("About this demo")
    st.markdown(
        "**CreatorPulse** flags creators at risk of burnout *before* it happens, "
        "so platforms can intervene early.\n\n"
        "**Methods demonstrated**\n"
        "- Survival analysis (Kaplan–Meier, Cox PH)\n"
        "- A/B test of a wellness intervention\n"
        "- Gradient-boosted burnout classifier\n"
        "- Causal inference (Difference-in-Differences)\n"
        "- Hypothesis testing + Bonferroni correction\n\n"
        "<span class='cp-pill'>SYNTHETIC DATA</span>",
        unsafe_allow_html=True,
    )
    st.caption("Author: Koutilya Yenumula")
    st.caption(f"Simulated creators: {len(R['creators_df'])} · "
               f"Weekly records: {len(R['ts_df']):,}")


creators_df = R["creators_df"]
overall_burnout = creators_df["burned_out"].mean()
roc_auc = roc_auc_score(R["y_test"], R["y_prob"])
pr_auc = average_precision_score(R["y_test"], R["y_prob"])

# ─────────────────────────────────────────────────────────────────────────────
# TOP-LINE METRICS (clearly labelled illustrative)
# ─────────────────────────────────────────────────────────────────────────────
st.markdown("### Key metrics  <small class='cp-illu'>(illustrative, from synthetic data)</small>",
            unsafe_allow_html=True)
m1, m2, m3, m4 = st.columns(4)
m1.metric("Simulated creators", f"{len(creators_df):,}")
m2.metric("Burnout rate (synthetic)", f"{overall_burnout:.1%}")
m3.metric("Model ROC-AUC", f"{roc_auc:.3f}", help="Burnout-risk classifier on held-out test set")
m4.metric("Model PR-AUC", f"{pr_auc:.3f}")

ab = R["ab"]
if {"treatment", "control"}.issubset(ab.index):
    lift = (ab.loc["treatment", "retention"] - ab.loc["control", "retention"]) / ab.loc["control", "retention"]
    n1, n2, n3 = st.columns(3)
    n1.metric("A/B retention lift (treatment)", f"+{lift:.0%}",
              help="8-week retention: wellness-check treatment vs control")
    n2.metric("DiD causal effect", f"{R['did_estimate']:+.2f} posts/wk",
              help="Difference-in-Differences: algorithm-change impact on posting pressure")
    n3.metric("DiD permutation p-value", f"{R['p_did']:.3f}")

st.divider()

# ─────────────────────────────────────────────────────────────────────────────
# TABS
# ─────────────────────────────────────────────────────────────────────────────
tab_dash, tab_surv, tab_ml, tab_causal, tab_data = st.tabs(
    ["🗂 Full Dashboard", "📉 Survival Analysis", "🤖 ML Model", "🧪 Causal / A-B", "🔢 Data"]
)

# ── TAB 1: the generated 6-panel dashboard image ─────────────────────────────
with tab_dash:
    st.markdown("#### Generated analysis dashboard")
    st.caption("Rendered live from the synthetic pipeline (6-panel matplotlib/seaborn).")

    # Build the 6-panel dashboard in-process (reusing the analysis objects) and
    # render it — no file dependency, always fresh.
    fig = plt.figure(figsize=(18, 11))
    import matplotlib.gridspec as gridspec
    gs = gridspec.GridSpec(2, 3, figure=fig, hspace=0.5, wspace=0.35)

    ax1 = fig.add_subplot(gs[0, 0])
    R["kmf_solo"].plot_survival_function(ax=ax1, ci_show=True, color="#e74c3c")
    R["kmf_team"].plot_survival_function(ax=ax1, ci_show=True, color="#2980b9")
    ax1.axhline(0.5, color="gray", ls="--", lw=0.8, alpha=0.7)
    ax1.set_title("Kaplan–Meier: Solo vs Team", fontweight="bold")
    ax1.set_xlabel("Weeks Active"); ax1.set_ylabel("Survival Prob (No Burnout)")
    ax1.set_ylim(0, 1.05); ax1.legend(fontsize=8)

    ax2 = fig.add_subplot(gs[0, 1])
    fpr, tpr, _ = roc_curve(R["y_test"], R["y_prob"])
    ax2.plot(fpr, tpr, color="#8e44ad", lw=2, label=f"AUC = {roc_auc:.3f}")
    ax2.plot([0, 1], [0, 1], color="gray", ls="--", lw=1, label="Random")
    ax2.fill_between(fpr, tpr, alpha=0.10, color="#8e44ad")
    ax2.set_title("ROC — Burnout Classifier", fontweight="bold")
    ax2.set_xlabel("False Positive Rate"); ax2.set_ylabel("True Positive Rate")
    ax2.legend(loc="lower right", fontsize=9); ax2.set_xlim(0, 1); ax2.set_ylim(0, 1.05)

    ax3 = fig.add_subplot(gs[0, 2])
    feat_imp = (pd.Series(R["gbm"].feature_importances_, index=R["feature_cols"])
                .sort_values().tail(10))
    colors = ["#e74c3c" if v > 0.05 else "#3498db" for v in feat_imp.values]
    feat_imp.plot(kind="barh", ax=ax3, color=colors, edgecolor="white")
    ax3.set_title("Top Feature Importances", fontweight="bold"); ax3.set_xlabel("Importance")

    ax4 = fig.add_subplot(gs[1, 0])
    arch = creators_df.groupby("archetype")["burned_out"].mean().sort_values(ascending=False)
    ac = ["#e74c3c" if v > 0.45 else "#f39c12" if v > 0.35 else "#2ecc71" for v in arch.values]
    arch.plot(kind="bar", ax=ax4, color=ac, edgecolor="white")
    ax4.set_title("Burnout Rate by Archetype", fontweight="bold")
    ax4.set_ylabel("Burnout Rate"); ax4.set_xlabel(""); ax4.set_ylim(0, 0.8)
    ax4.tick_params(axis="x", rotation=30)

    ax5 = fig.add_subplot(gs[1, 1])
    plat = creators_df.groupby("platform")["burned_out"].mean().sort_values(ascending=False)
    plat.plot(kind="bar", ax=ax5, color=["#e74c3c", "#f39c12", "#3498db", "#2ecc71"][:len(plat)],
              edgecolor="white")
    ax5.set_title("Burnout Rate by Platform", fontweight="bold")
    ax5.set_ylabel("Burnout Rate"); ax5.set_xlabel(""); ax5.set_ylim(0, 0.8)
    ax5.tick_params(axis="x", rotation=30)

    ax6 = fig.add_subplot(gs[1, 2])
    cp_stats = R["cohort_stats"]["burnout_rate"].reset_index()
    ax6.bar(cp_stats["tenure_cohort"].astype(str), cp_stats["burnout_rate"],
            color=["#3498db", "#f39c12", "#e67e22", "#e74c3c"][:len(cp_stats)], edgecolor="white")
    ax6.set_title("Burnout Rate by Tenure", fontweight="bold")
    ax6.set_xlabel("Tenure Cohort"); ax6.set_ylabel("Burnout Rate"); ax6.set_ylim(0, 0.8)

    fig.suptitle("CreatorPulse — Burnout Early-Warning System (synthetic data)",
                 fontsize=14, fontweight="bold", y=1.0)
    st.pyplot(fig, clear_figure=True)

    # Also offer the pre-rendered PNG if it ships with the repo.
    png = os.path.join(os.path.dirname(__file__), "creatorpulse_dashboard.png")
    if os.path.exists(png):
        with open(png, "rb") as fh:
            st.download_button("⬇️ Download dashboard PNG", fh, file_name="creatorpulse_dashboard.png",
                               mime="image/png")

# ── TAB 2: Survival ──────────────────────────────────────────────────────────
with tab_surv:
    st.markdown("#### Kaplan–Meier survival: Solo vs Team creators")
    st.caption("Survival = probability a creator has *not* burned out by week *t*. "
               "Synthetic data.")
    figs, axs = plt.subplots(figsize=(9, 5))
    R["kmf_solo"].plot_survival_function(ax=axs, ci_show=True, color="#e74c3c")
    R["kmf_team"].plot_survival_function(ax=axs, ci_show=True, color="#2980b9")
    axs.axhline(0.5, color="gray", ls="--", lw=0.8, alpha=0.7, label="S(t)=0.5")
    axs.set_xlabel("Weeks Active"); axs.set_ylabel("Survival Probability (No Burnout)")
    axs.set_ylim(0, 1.05); axs.legend()
    st.pyplot(figs, clear_figure=True)

    sd = R["survival_df"]
    solo_n = int((sd["team_size"] == 1).sum())
    team_n = int((sd["team_size"] > 1).sum())
    c1, c2 = st.columns(2)
    c1.metric("Solo creators (synthetic)", f"{solo_n}")
    c2.metric("Team creators (synthetic)", f"{team_n}")
    st.info("Interpretation (illustrative): solo creators tend to 'survive' (avoid burnout) "
            "for fewer weeks than creators backed by a team.")

# ── TAB 3: ML model ──────────────────────────────────────────────────────────
with tab_ml:
    st.markdown("#### Burnout-risk classifier (Gradient Boosting)")
    cols = st.columns(2)
    with cols[0]:
        st.caption("ROC curve — held-out test set (synthetic).")
        f1, a1 = plt.subplots(figsize=(6, 5))
        fpr, tpr, _ = roc_curve(R["y_test"], R["y_prob"])
        a1.plot(fpr, tpr, color="#8e44ad", lw=2, label=f"AUC = {roc_auc:.3f}")
        a1.plot([0, 1], [0, 1], color="gray", ls="--", lw=1, label="Random")
        a1.fill_between(fpr, tpr, alpha=0.10, color="#8e44ad")
        a1.set_xlabel("False Positive Rate"); a1.set_ylabel("True Positive Rate")
        a1.legend(loc="lower right"); a1.set_xlim(0, 1); a1.set_ylim(0, 1.05)
        st.pyplot(f1, clear_figure=True)
    with cols[1]:
        st.caption("Feature importances — what drives the burnout signal (synthetic).")
        f2, a2 = plt.subplots(figsize=(6, 5))
        fi = (pd.Series(R["gbm"].feature_importances_, index=R["feature_cols"])
              .sort_values().tail(10))
        colors = ["#e74c3c" if v > 0.05 else "#3498db" for v in fi.values]
        fi.plot(kind="barh", ax=a2, color=colors, edgecolor="white")
        a2.set_xlabel("Importance Score")
        st.pyplot(f2, clear_figure=True)

    mm1, mm2 = st.columns(2)
    mm1.metric("ROC-AUC", f"{roc_auc:.3f}")
    mm2.metric("PR-AUC", f"{pr_auc:.3f}")
    st.caption("Features are engineered from weeks 1–52 only (leakage-free) before the "
               "burnout window — a deliberate guard against target leakage.")

# ── TAB 4: Causal / A-B ──────────────────────────────────────────────────────
with tab_causal:
    st.markdown("#### Difference-in-Differences: did an algorithm change raise posting pressure?")
    st.metric("DiD causal estimate", f"{R['did_estimate']:+.3f} posts/week",
              help="(ΔTikTok) − (ΔInstagram) around the week-52 change")
    p_did = R["p_did"]
    verdict = "causally increased" if p_did < 0.05 else "did NOT causally increase"
    st.write(f"Permutation-test p-value: **{p_did:.4f}** → the algorithm change "
             f"**{verdict}** posting pressure (synthetic data).")

    st.divider()
    st.markdown("#### A/B test: wellness-check intervention")
    ab = R["ab"]
    abv = ab.rename(columns={"n": "N", "resolved": "burnout_resolved_rate",
                             "retention": "avg_8w_retention"})
    st.dataframe(abv.style.format({"burnout_resolved_rate": "{:.1%}",
                                   "avg_8w_retention": "{:.1%}"}),
                 use_container_width=True)
    if {"treatment", "control"}.issubset(ab.index):
        lift = (ab.loc["treatment", "retention"] - ab.loc["control", "retention"]) / ab.loc["control", "retention"]
        st.success(f"Treatment lifts 8-week retention by **+{lift:.0%}** vs control (illustrative).")

    st.divider()
    st.markdown("#### Hypothesis tests (Bonferroni-corrected, α = 0.0167)")
    thr = 0.05 / 3
    tests = pd.DataFrame({
        "Test": ["Mann–Whitney U (engagement)", "Welch t-test (posts/week)",
                 "Chi-square (platform × burnout)"],
        "p-value": [R["p_mw"], R["p_ttest"], R["p_chi2"]],
    })
    tests["Significant (Bonferroni)"] = np.where(tests["p-value"] < thr, "✅ yes", "❌ no")
    st.dataframe(tests.style.format({"p-value": "{:.2e}"}), use_container_width=True)

# ── TAB 5: Data ──────────────────────────────────────────────────────────────
with tab_data:
    st.markdown("#### Synthetic creator profiles (sample)")
    st.caption("Generated by the behavioral simulator — not real people.")
    st.dataframe(creators_df.head(50), use_container_width=True)
    st.markdown("#### Weekly time-series (sample)")
    st.dataframe(R["ts_df"].head(50), use_container_width=True)

st.divider()
st.caption("CreatorPulse demo · 100% synthetic, illustrative data · "
           "Built with Streamlit. Methodology only — not a real-world dataset.")
